branch-defaults:
  fix_beanstalk:
    environment: testinguser
environment-defaults:
  bboeisgreat:
    branch: null
    repository: null
global:
  application_name: TheFakeBBoe
  branch: null
  default_ec2_keyname: TheFakeBBoe
  default_platform: Ruby 2.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
