version: '3'

services:
  tsung:
    build: .
    ports:
    - "8091:8091"
    command: tsung start
    volumes:
      - ./simple.xml:/root/.tsung/tsung.xml:ro
      - ./profile.xml:/root/.tsung/tsung2.xml:ro
      - ./bin/:/root/.tsung/bin/:ro
      - ./logs/:/root/.tsung/log
    network_mode: host

